services:
  - type: web
    name: micro-app-final-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://micro-app-final-backend.onrender.com
      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyA5mjFUZbFzcLzInqBXSB-LILWKrOSQ_4A
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: micro-ai-5df30.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: micro-ai-5df30
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: micro-ai-5df30.firebasestorage.app
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: 290991587661
      - key: VITE_FIREBASE_APP_ID
        value: 1:290991587661:web:9b58158b4af3a19b107704 
